baseURL = 'https://saligrama.io'
languageCode = 'en-us'
title = 'Aditya Saligrama'
theme = 'hugo-theme-hello-friend'

paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # Enable to show reading time in minutes for posts
  showReadingTime = false

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[languages]
  [languages.en]
    title = 'Aditya Saligrama'
    subtitle = ""
    keywords = ""
    copyright = "f"
    menuMore = "Show more"
    showMenuItems = 5
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "Aditya Saligrama"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/blog"
      [[languages.en.menu.main]]
        identifier = "notes"
        name = "Notes"
        url = "/notes"
      [[languages.en.menu.main]]
        identifier = "photo"
        name = "Photography"
        url = "/photo"